import { z } from "zod";
import { RISK_V1 } from "./params.ts";
import type { Finding, GuardResult, RecordedFinding, Severity } from "./types.ts";

/**
 * The finding codes the model may emit, in the fixed order of the P5 plan's Decision 8. A new code
 * is a schema change before the first live verdict, and a new tag after it (the evidence format
 * freezes once one exists).
 */
export const MODEL_FINDING_CODES = [
  "FUNDS_FORWARDED",
  "UNMANDATED_RECIPIENT",
  "NEW_CONTRACT",
  "FRESH_COUNTERPARTY",
  "MANDATE_VIOLATION",
  "PERMISSION_CHANGE",
  "SIMULATION_FAILED",
  "LOW_REPUTATION",
  "RISKY_LABEL",
  "SUSPICIOUS_CALLDATA",
  "OTHER",
] as const;

/** A code the model is allowed to emit (checked by {@link findingsJsonSchema} and {@link parseModelOutput}). */
export type ModelFindingCode = (typeof MODEL_FINDING_CODES)[number];

/**
 * The one finding code only code may add (Decision 8, Decision 13): never accepted from the model,
 * because {@link MODEL_FINDING_CODES} excludes it, so a model answer naming it fails parsing exactly
 * like any other unknown code.
 */
export const PROMPT_INJECTION_SUSPECTED = "PROMPT_INJECTION_SUSPECTED" as const;

/** Every finding code that code itself can add, never the model. Currently just the one. */
export const CODE_FINDING_CODES = [PROMPT_INJECTION_SUSPECTED] as const;

/** The seven read-only tools (Decision 16), in the P5 plan's table order. */
export const TOOL_NAMES = [
  "get_mandate",
  "simulate_action",
  "recent_permission_events",
  "counterparty_onchain",
  "erc8004_reputation",
  "nansen_counterparty_profile",
  "nansen_flows",
] as const;

/** One of the seven tools a finding, or an `<untrusted_data>` block, can be attributed to. */
export type ToolName = (typeof TOOL_NAMES)[number];

/**
 * Every name a model finding's `sources` may cite (Decision 8): the request, validator A's verdict,
 * or one of the seven tools — but only when that source was actually used in this run, which
 * {@link parseModelOutput}'s `called` argument checks separately (not everything here is cite-able on
 * every run).
 */
export const SOURCE_NAMES = ["request", "mandate_v1_verdict", ...TOOL_NAMES] as const;

/** A name {@link SOURCE_NAMES} lists as citable in principle (still subject to the per-run `called` check). */
export type SourceName = (typeof SOURCE_NAMES)[number];

/**
 * The JSON Schema sent as `response_format.json_schema.schema` on the final, tool-free call, with
 * `strict: true` (Groq's constrained decoding): every object lists every one of its properties in
 * `required` and sets `additionalProperties: false`, and `code`/`severity`/`sources` are enums, as
 * Groq's strict mode requires. Lengths and counts (`maxItems`, `maxLength`) are left to zod instead,
 * since Groq doesn't document support for them. A plain object literal, not generated by a library,
 * so it can't silently drift from what {@link parseModelOutput} actually enforces.
 */
export const findingsJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: ["findings"],
  properties: {
    findings: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["code", "severity", "explanation", "sources"],
        properties: {
          code: { type: "string", enum: [...MODEL_FINDING_CODES] },
          severity: { type: "string", enum: ["low", "medium", "high"] },
          explanation: { type: "string" },
          sources: {
            type: "array",
            items: { type: "string", enum: [...SOURCE_NAMES] },
          },
        },
      },
    },
  },
} as const;

const findingSchema = z.strictObject({
  code: z.enum(MODEL_FINDING_CODES),
  severity: z.enum(["low", "medium", "high"]),
  explanation: z.string().max(RISK_V1.maxExplanationChars),
  sources: z.array(z.enum(SOURCE_NAMES)).min(1).max(RISK_V1.maxSourcesPerFinding),
});

const findingsDocSchema = z.strictObject({
  findings: z.array(findingSchema).max(RISK_V1.maxFindings),
});

function isJsonObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** `findings[2].sources[0]`-style path, from a zod issue's `path` (numbers are array indices). */
function formatPath(path: ReadonlyArray<string | number>): string {
  let out = "";
  for (let i = 0; i < path.length; i++) {
    const key = path[i];
    if (typeof key === "number") out += `[${key}]`;
    else out += i === 0 ? key : `.${key}`;
  }
  return out;
}

/**
 * The first zod issue, turned into our own fixed-text error (never a library's message, because it
 * can end up in hashed evidence and logs — the style of `validators/mandate/src/collect.ts`'s
 * `parseApprovalParts`). Two shapes get a clearer phrase than the generic `invalid at <path>`: the
 * findings array itself over length, and one finding's `explanation` over length.
 */
function errorFromIssue(issue: { code: string; path: ReadonlyArray<string | number> }): string {
  const { code, path } = issue;
  if (code === "too_big" && path.length === 1 && path[0] === "findings") {
    return "too many findings";
  }
  if (code === "too_big" && path.length === 3 && path[0] === "findings" && path[2] === "explanation") {
    return `explanation too long at findings[${path[1]}]`;
  }
  const formatted = formatPath(path);
  return `invalid at ${formatted === "" ? "root" : formatted}`;
}

/**
 * Parses the final call's raw content into findings, strictly (ARCHITECTURE "Findings and score";
 * Decision 8). Never throws. `raw` may have leading or trailing whitespace (`JSON.parse` already
 * tolerates it); anything else that isn't exactly `{findings: [...]}` fails.
 *
 * `called` is the set of source names citable in this run: the caller passes the tool names actually
 * called, plus `"request"` and `"mandate_v1_verdict"` (always citable, since the model always sees
 * both). A `sources` entry that names a real source from {@link SOURCE_NAMES} but isn't in `called`
 * fails with `source <name> was not called` — checked after the schema, in finding and source order,
 * so the first offending name is reported. A `sources` entry that isn't in {@link SOURCE_NAMES} at all
 * (including `"classifier:…"`, which only code may use) fails the schema instead, with the generic
 * `invalid at findings[i].sources[j]`.
 *
 * Every other error is our own fixed text: `"not JSON"` (including an empty string, or JSON wrapped
 * in prose or code fences, since none of those parse), `"not a JSON object"`, `"too many findings"`,
 * `"explanation too long at findings[i]"`, or the generic `"invalid at <path>"` (an unknown or
 * reserved `code`, a bad `severity`, too few or too many `sources`, an extra key, …).
 */
export function parseModelOutput(
  raw: string,
  called: ReadonlySet<string>,
): { ok: true; findings: Finding[] } | { ok: false; error: string } {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return { ok: false, error: "not JSON" };
  }
  if (!isJsonObject(parsed)) return { ok: false, error: "not a JSON object" };

  const result = findingsDocSchema.safeParse(parsed);
  if (!result.success) {
    const issue = result.error.issues[0];
    if (issue === undefined) return { ok: false, error: "invalid at root" };
    // zod's `path` is `PropertyKey[]` (it allows a `symbol` in principle); our schema never produces
    // one, but the fixed-text formatter only needs to handle strings and array indices.
    const path = issue.path.map((key) => (typeof key === "symbol" ? String(key) : key));
    return { ok: false, error: errorFromIssue({ code: issue.code, path }) };
  }

  for (let i = 0; i < result.data.findings.length; i++) {
    const finding = result.data.findings[i];
    if (finding === undefined) continue;
    for (const source of finding.sources) {
      if (!called.has(source)) return { ok: false, error: `source ${source} was not called` };
    }
  }

  return { ok: true, findings: result.data.findings };
}

/**
 * The score from findings alone (Decision 9): 100 with none, 80 if every one is `low`, 40 if any is
 * `medium`, 0 if any is `high`. Only the severities are read, so this takes model findings and code
 * findings (and the `RecordedFinding`s evidence holds) alike.
 */
export function scoreOf(findings: readonly { severity: Severity }[]): 0 | 40 | 80 | 100 {
  if (findings.some((f) => f.severity === "high")) return RISK_V1.scores.high;
  if (findings.some((f) => f.severity === "medium")) return RISK_V1.scores.medium;
  if (findings.length > 0) return RISK_V1.scores.low;
  return RISK_V1.scores.none;
}

/**
 * The one `PROMPT_INJECTION_SUSPECTED` finding code adds when Prompt Guard flagged any screened
 * field (Decision 13), or `null` when none were flagged. `results` is screened in call order; the
 * finding's `sources` name the flagged ones only, as `"classifier:" + source`, in that same order.
 */
export function injectionFinding(results: readonly GuardResult[]): RecordedFinding | null {
  const flagged = results.filter((r) => r.flagged);
  if (flagged.length === 0) return null;
  const sourceList = flagged.map((r) => r.source).join(", ");
  return {
    code: PROMPT_INJECTION_SUSPECTED,
    severity: "medium",
    explanation: `Untrusted text in ${sourceList} was classified as a likely prompt injection (score >= 0.5); treat this action as suspicious.`,
    sources: flagged.map((r) => `classifier:${r.source}`),
    origin: "code",
  };
}
